[2021-12-01 18:16:45,417: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 18:16:45,437: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 18:16:46,473: INFO/MainProcess] mingle: all alone
[2021-12-01 18:16:46,507: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-01 18:16:46,527: INFO/MainProcess] celery@3c63a915ee4f ready.
[2021-12-01 18:23:53,270: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 18:23:53,493: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 18:23:54,618: INFO/MainProcess] mingle: all alone
[2021-12-01 18:23:54,651: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-01 18:23:54,657: INFO/MainProcess] celery@771a9167ac5e ready.
[2021-12-01 18:26:42,409: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 18:26:42,526: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 18:26:43,758: INFO/MainProcess] mingle: all alone
[2021-12-01 18:26:43,782: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-01 18:26:43,783: INFO/MainProcess] celery@82a85a29d0d7 ready.
[2021-12-01 18:32:53,114: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 18:32:53,135: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 18:32:54,192: INFO/MainProcess] mingle: all alone
[2021-12-01 18:32:54,215: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-01 18:32:54,217: INFO/MainProcess] celery@110d6cb7dcc2 ready.
[2021-12-01 18:32:55,524: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-01 18:35:00,808: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-01 18:35:00,828: INFO/MainProcess] mingle: searching for neighbors
[2021-12-01 18:35:01,881: INFO/MainProcess] mingle: all alone
[2021-12-01 18:35:01,914: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-01 18:35:01,916: INFO/MainProcess] celery@6d59da90e2d1 ready.
[2021-12-01 18:35:03,953: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-06 19:33:00,628: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-06 19:33:00,649: INFO/MainProcess] mingle: searching for neighbors
[2021-12-06 19:33:01,688: INFO/MainProcess] mingle: all alone
[2021-12-06 19:33:01,715: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-06 19:33:01,717: INFO/MainProcess] celery@8831f0682204 ready.
[2021-12-06 19:33:04,853: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-07 15:21:09,036: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-07 15:21:09,057: INFO/MainProcess] mingle: searching for neighbors
[2021-12-07 15:21:10,098: INFO/MainProcess] mingle: all alone
[2021-12-07 15:21:10,246: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-07 15:21:10,250: INFO/MainProcess] celery@84d13aba0912 ready.
[2021-12-07 15:21:17,731: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-07 15:22:25,203: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-07 15:22:25,259: INFO/MainProcess] mingle: searching for neighbors
[2021-12-07 15:22:26,334: INFO/MainProcess] mingle: all alone
[2021-12-07 15:22:26,382: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-07 15:22:26,384: INFO/MainProcess] celery@84d13aba0912 ready.
[2021-12-07 15:22:35,494: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-07 17:41:58,582: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-07 17:41:58,625: INFO/MainProcess] mingle: searching for neighbors
[2021-12-07 17:41:59,778: INFO/MainProcess] mingle: all alone
[2021-12-07 17:43:21,664: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-07 17:43:21,712: INFO/MainProcess] celery@7b05fee06316 ready.
[2021-12-07 17:43:25,593: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-07 19:14:32,743: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-07 19:14:32,839: INFO/MainProcess] mingle: searching for neighbors
[2021-12-07 19:14:33,978: INFO/MainProcess] mingle: all alone
[2021-12-07 19:14:34,072: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-07 19:14:34,074: INFO/MainProcess] celery@7f1bc072aa27 ready.
[2021-12-07 19:14:52,315: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 19:38:46,790: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 19:38:46,894: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 19:38:48,062: INFO/MainProcess] mingle: all alone
[2021-12-08 19:38:48,171: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 19:38:48,174: INFO/MainProcess] celery@3c9251b4dc7f ready.
[2021-12-08 19:39:00,340: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 19:44:03,192: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 19:44:03,215: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 19:44:04,269: INFO/MainProcess] mingle: all alone
[2021-12-08 19:44:04,304: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 19:44:04,305: INFO/MainProcess] celery@7e6e5077fc34 ready.
[2021-12-08 19:44:12,410: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 19:50:55,637: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 19:50:55,677: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 19:50:56,756: INFO/MainProcess] mingle: all alone
[2021-12-08 19:50:56,790: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 19:50:56,792: INFO/MainProcess] celery@be1b3ef8c866 ready.
[2021-12-08 19:51:05,433: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 20:29:00,613: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 20:29:00,646: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 20:29:01,702: INFO/MainProcess] mingle: all alone
[2021-12-08 20:29:01,732: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 20:29:01,734: INFO/MainProcess] celery@f810ee7aac98 ready.
[2021-12-08 20:29:09,809: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 20:57:56,309: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 20:57:56,341: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 20:57:57,426: INFO/MainProcess] mingle: all alone
[2021-12-08 20:57:57,488: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 20:57:57,491: INFO/MainProcess] celery@5b8c7af6e377 ready.
[2021-12-08 20:58:05,607: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 21:08:07,037: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 21:08:07,082: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 21:08:08,204: INFO/MainProcess] mingle: all alone
[2021-12-08 21:08:08,270: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 21:08:08,272: INFO/MainProcess] celery@62284ba8d7fb ready.
[2021-12-08 21:08:17,588: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-08 21:49:43,709: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-08 21:49:43,745: INFO/MainProcess] mingle: searching for neighbors
[2021-12-08 21:49:44,803: INFO/MainProcess] mingle: all alone
[2021-12-08 21:49:44,844: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-08 21:49:44,845: INFO/MainProcess] celery@701cae98bcc0 ready.
[2021-12-08 21:49:50,188: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 13:23:53,690: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-09 13:23:53,790: INFO/MainProcess] mingle: searching for neighbors
[2021-12-09 13:23:55,020: INFO/MainProcess] mingle: all alone
[2021-12-09 13:23:55,074: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-09 13:23:55,076: INFO/MainProcess] celery@7b1ea1d4d9fe ready.
[2021-12-09 13:24:01,976: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 14:01:13,829: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-09 14:01:13,862: INFO/MainProcess] mingle: searching for neighbors
[2021-12-09 14:01:14,908: INFO/MainProcess] mingle: all alone
[2021-12-09 14:01:14,943: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-09 14:01:14,944: INFO/MainProcess] celery@5b237b01f633 ready.
[2021-12-09 14:01:24,578: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 14:09:59,479: DEBUG/MainProcess] | Worker: Preparing bootsteps.
[2021-12-09 14:09:59,494: DEBUG/MainProcess] | Worker: Building graph...
[2021-12-09 14:09:59,497: DEBUG/MainProcess] | Worker: New boot order: {Timer, Hub, Pool, Autoscaler, StateDB, Beat, Consumer}
[2021-12-09 14:09:59,550: DEBUG/MainProcess] | Consumer: Preparing bootsteps.
[2021-12-09 14:09:59,552: DEBUG/MainProcess] | Consumer: Building graph...
[2021-12-09 14:09:59,622: DEBUG/MainProcess] | Consumer: New boot order: {Connection, Events, Mingle, Tasks, Control, Agent, Heart, Gossip, event loop}
[2021-12-09 14:09:59,669: DEBUG/MainProcess] | Worker: Starting Hub
[2021-12-09 14:09:59,671: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:09:59,673: DEBUG/MainProcess] | Worker: Starting Pool
[2021-12-09 14:10:02,240: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:02,243: DEBUG/MainProcess] | Worker: Starting Consumer
[2021-12-09 14:10:02,245: DEBUG/MainProcess] | Consumer: Starting Connection
[2021-12-09 14:10:02,371: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-09 14:10:02,373: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:02,374: DEBUG/MainProcess] | Consumer: Starting Events
[2021-12-09 14:10:02,405: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:02,406: DEBUG/MainProcess] | Consumer: Starting Mingle
[2021-12-09 14:10:02,408: INFO/MainProcess] mingle: searching for neighbors
[2021-12-09 14:10:03,494: INFO/MainProcess] mingle: all alone
[2021-12-09 14:10:03,497: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:03,500: DEBUG/MainProcess] | Consumer: Starting Tasks
[2021-12-09 14:10:03,529: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:03,531: DEBUG/MainProcess] | Consumer: Starting Control
[2021-12-09 14:10:03,559: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:03,561: DEBUG/MainProcess] | Consumer: Starting Heart
[2021-12-09 14:10:03,578: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:03,580: DEBUG/MainProcess] | Consumer: Starting Gossip
[2021-12-09 14:10:03,592: DEBUG/MainProcess] ^-- substep ok
[2021-12-09 14:10:03,593: DEBUG/MainProcess] | Consumer: Starting event loop
[2021-12-09 14:10:03,594: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2021-12-09 14:10:03,599: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-09 14:10:03,600: INFO/MainProcess] celery@c2711ce36b3b ready.
[2021-12-09 14:10:03,602: DEBUG/MainProcess] basic.qos: prefetch_count->16
[2021-12-09 14:10:07,093: DEBUG/MainProcess] pidbox received method stats() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'c0c8d13a-5b96-3e72-9cc4-8c5a1ad3ce72'} ticket:5ebf3176-8200-455c-9d1a-38cfa34b9c70]
[2021-12-09 14:10:07,107: DEBUG/MainProcess] pidbox received method heartbeat() [reply_to:None ticket:None]
[2021-12-09 14:10:07,109: DEBUG/MainProcess] Heartbeat requested by remote.
[2021-12-09 14:10:07,112: DEBUG/MainProcess] pidbox received method registered(taskinfoitems=[]) [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '487c8963-22eb-3aa2-b8c7-6df96b8843f4'} ticket:84bb7ab7-d7fc-4fc5-a007-b3cafea7d1e7]
[2021-12-09 14:10:07,122: DEBUG/MainProcess] pidbox received method active_queues() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'd253b165-7327-3189-ad26-5c610af8dbf0'} ticket:ddf45295-9192-4547-82d8-70a847b37d0f]
[2021-12-09 14:10:07,126: DEBUG/MainProcess] pidbox received method scheduled() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'a51b557c-7e0e-38cf-84ab-91e6f379f80d'} ticket:a8423cbc-1b97-43cc-b9b1-a844445a3cb3]
[2021-12-09 14:10:07,131: DEBUG/MainProcess] pidbox received method reserved() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'ad100739-2dbf-3b23-b329-fd726710c89c'} ticket:3cad0e67-1ca3-4be3-8b8e-af343ad12cb3]
[2021-12-09 14:10:07,135: DEBUG/MainProcess] pidbox received method active(safe=None) [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'fdebc8ff-8682-30ab-a5ad-6844091a4e31'} ticket:52b17cbc-9d1d-43d5-ac99-6167052e034b]
[2021-12-09 14:10:07,141: DEBUG/MainProcess] pidbox received method conf(with_defaults=False) [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'b0165fed-e91b-3686-b417-4bfc733367b4'} ticket:3a8c5828-9ebe-4848-b592-f80883256782]
[2021-12-09 14:10:07,188: DEBUG/MainProcess] pidbox received method revoked() [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': '48da9d3d-5222-39c3-8c9b-b049e31702f3'} ticket:93a20fd8-60fa-44fb-8c9d-91bc1e7156c2]
[2021-12-09 14:10:11,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:11,855: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 14:10:16,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:21,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:26,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:31,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:36,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:51,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:10:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:01,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:06,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:11,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:16,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:21,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:26,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:31,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:36,880: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:41,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:51,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:11:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:06,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:11,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:16,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:26,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:36,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:41,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:51,990: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:12:56,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:01,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:06,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:11,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:16,861: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:21,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:26,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:31,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:36,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:41,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:51,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:13:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:02,172: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:06,861: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:11,858: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:16,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:21,858: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:26,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:31,859: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:36,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:46,859: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:51,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:14:56,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:06,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:11,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:16,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:26,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:31,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:36,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:51,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:15:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:01,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:06,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:11,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:16,858: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:26,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:36,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:41,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:46,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:51,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:16:56,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:06,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:11,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:16,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:26,858: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:31,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:36,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:51,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:17:56,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:01,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:06,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:11,859: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:16,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:21,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:26,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:31,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:36,859: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:46,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:51,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:18:56,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:06,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:11,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:16,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:21,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:26,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:36,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:41,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:46,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:51,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:19:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:06,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:11,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:16,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:26,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:37,125: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:41,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:46,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:51,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:20:56,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:01,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:06,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:11,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:16,856: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:21,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:26,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:36,861: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:41,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:51,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:21:56,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:01,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:06,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:11,853: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:16,857: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:21,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:26,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:31,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:36,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:41,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:46,855: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:51,854: DEBUG/MainProcess] pidbox received method enable_events() [reply_to:None ticket:None]
[2021-12-09 14:22:59,878: DEBUG/MainProcess] | Worker: Closing Hub...
[2021-12-09 14:22:59,880: DEBUG/MainProcess] | Worker: Closing Pool...
[2021-12-09 14:22:59,921: DEBUG/MainProcess] | Worker: Closing Consumer...
[2021-12-09 14:22:59,923: DEBUG/MainProcess] | Worker: Stopping Consumer...
[2021-12-09 14:22:59,933: DEBUG/MainProcess] | Consumer: Closing Connection...
[2021-12-09 14:22:59,937: DEBUG/MainProcess] | Consumer: Closing Events...
[2021-12-09 14:22:59,939: DEBUG/MainProcess] | Consumer: Closing Mingle...
[2021-12-09 14:22:59,940: DEBUG/MainProcess] | Consumer: Closing Tasks...
[2021-12-09 14:22:59,942: DEBUG/MainProcess] | Consumer: Closing Control...
[2021-12-09 14:22:59,942: DEBUG/MainProcess] | Consumer: Closing Heart...
[2021-12-09 14:22:59,943: DEBUG/MainProcess] | Consumer: Closing Gossip...
[2021-12-09 14:22:59,944: DEBUG/MainProcess] | Consumer: Closing event loop...
[2021-12-09 14:22:59,945: DEBUG/MainProcess] | Consumer: Stopping event loop...
[2021-12-09 14:22:59,946: DEBUG/MainProcess] | Consumer: Stopping Gossip...
[2021-12-09 14:23:00,066: DEBUG/MainProcess] | Consumer: Stopping Heart...
[2021-12-09 14:23:00,072: DEBUG/MainProcess] | Consumer: Stopping Control...
[2021-12-09 14:23:00,083: DEBUG/MainProcess] | Consumer: Stopping Tasks...
[2021-12-09 14:23:00,096: DEBUG/MainProcess] Canceling task consumer...
[2021-12-09 14:23:00,099: DEBUG/MainProcess] | Consumer: Stopping Mingle...
[2021-12-09 14:23:00,101: DEBUG/MainProcess] | Consumer: Stopping Events...
[2021-12-09 14:23:00,102: DEBUG/MainProcess] | Consumer: Stopping Connection...
[2021-12-09 14:23:00,110: DEBUG/MainProcess] | Worker: Stopping Pool...
[2021-12-09 14:23:01,378: DEBUG/MainProcess] | Worker: Stopping Hub...
[2021-12-09 14:23:01,381: DEBUG/MainProcess] | Consumer: Shutdown Gossip...
[2021-12-09 14:23:01,383: DEBUG/MainProcess] | Consumer: Shutdown Heart...
[2021-12-09 14:23:01,391: DEBUG/MainProcess] | Consumer: Shutdown Control...
[2021-12-09 14:23:01,393: DEBUG/MainProcess] | Consumer: Shutdown Tasks...
[2021-12-09 14:23:01,395: DEBUG/MainProcess] Canceling task consumer...
[2021-12-09 14:23:01,398: DEBUG/MainProcess] Closing consumer channel...
[2021-12-09 14:23:01,400: DEBUG/MainProcess] | Consumer: Shutdown Events...
[2021-12-09 14:23:01,407: DEBUG/MainProcess] | Consumer: Shutdown Connection...
[2021-12-09 14:23:01,493: DEBUG/MainProcess] removing tasks from inqueue until task handler finished
[2021-12-09 14:28:20,465: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 2.00 seconds... (1/100)

[2021-12-09 14:28:22,482: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 4.00 seconds... (2/100)

[2021-12-09 14:28:26,494: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 6.00 seconds... (3/100)

[2021-12-09 14:28:32,510: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 8.00 seconds... (4/100)

[2021-12-09 14:28:40,528: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 10.00 seconds... (5/100)

[2021-12-09 14:28:50,550: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 12.00 seconds... (6/100)

[2021-12-09 14:29:02,615: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 14.00 seconds... (7/100)

[2021-12-09 14:29:16,678: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 16.00 seconds... (8/100)

[2021-12-09 14:29:32,715: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 18.00 seconds... (9/100)

[2021-12-09 14:29:50,785: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 20.00 seconds... (10/100)

[2021-12-09 14:30:10,823: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 22.00 seconds... (11/100)

[2021-12-09 14:30:32,864: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 24.00 seconds... (12/100)

[2021-12-09 14:30:56,914: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 26.00 seconds... (13/100)

[2021-12-09 14:31:22,964: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 28.00 seconds... (14/100)

[2021-12-09 14:31:51,007: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 30.00 seconds... (15/100)

[2021-12-09 14:32:21,055: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:32:53,102: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:33:25,151: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:33:57,199: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:34:29,247: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:35:01,297: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:35:33,348: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:36:05,395: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:36:37,447: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:37:09,494: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:37:41,539: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:38:13,586: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:38:45,633: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:39:17,678: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:39:49,724: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:40:21,771: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:40:53,816: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:41:25,976: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:41:58,087: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:42:30,199: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:43:02,247: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:43:34,942: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 111] Connection refused.
Trying again in 32.00 seconds... (16/100)

[2021-12-09 14:44:44,469: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-09 14:44:44,507: INFO/MainProcess] mingle: searching for neighbors
[2021-12-09 14:44:45,558: INFO/MainProcess] mingle: all alone
[2021-12-09 14:44:45,606: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:205: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory
[2021-12-09 14:44:45,608: INFO/MainProcess] celery@a03d088299cf ready.
[2021-12-09 14:44:47,072: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 14:46:36,679: INFO/MainProcess] Received task: ContactForm.tasks.queue_send_message_as_email[9b3af59a-2bd4-4fa7-a79c-01a9a5bce8a9]  
[2021-12-09 14:46:38,984: INFO/ForkPoolWorker-1] Task ContactForm.tasks.queue_send_message_as_email[9b3af59a-2bd4-4fa7-a79c-01a9a5bce8a9] succeeded in 2.2926914999989094s: True
[2021-12-09 14:59:38,053: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-09 14:59:38,083: INFO/MainProcess] mingle: searching for neighbors
[2021-12-09 14:59:39,122: INFO/MainProcess] mingle: all alone
[2021-12-09 14:59:39,146: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-09 14:59:39,148: INFO/MainProcess] celery@272e71734e6b ready.
[2021-12-09 14:59:40,360: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-09 15:01:24,360: INFO/MainProcess] Task ContactForm.tasks.queue_send_message_as_email[e6548459-f83b-4f54-8c13-b34595d6e837] received
[2021-12-09 15:01:27,858: INFO/ForkPoolWorker-1] Task ContactForm.tasks.queue_send_message_as_email[e6548459-f83b-4f54-8c13-b34595d6e837] succeeded in 3.099096699996153s: True
[2021-12-13 15:21:54,747: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-13 15:21:54,810: INFO/MainProcess] mingle: searching for neighbors
[2021-12-13 15:21:55,896: INFO/MainProcess] mingle: all alone
[2021-12-13 15:21:55,943: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-13 15:21:55,945: INFO/MainProcess] celery@894a35fba408 ready.
[2021-12-13 15:21:59,647: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-13 18:31:31,068: INFO/MainProcess] Task ContactForm.tasks.queue_send_message_as_email[a53e7d65-648f-4f66-91be-d3625c39aad2] received
[2021-12-13 18:31:35,270: INFO/ForkPoolWorker-1] Task ContactForm.tasks.queue_send_message_as_email[a53e7d65-648f-4f66-91be-d3625c39aad2] succeeded in 3.8680954999999813s: True
[2021-12-14 14:18:04,400: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 326, in start
    blueprint.start(self)
  File "/usr/local/lib/python3.9/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py", line 618, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python3.9/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/usr/local/lib/python3.9/site-packages/kombu/asynchronous/hub.py", line 306, in create_loop
    events = poll(poll_timeout)
  File "/usr/local/lib/python3.9/site-packages/kombu/utils/eventio.py", line 81, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/usr/local/lib/python3.9/site-packages/celery/apps/worker.py", line 290, in _handle_request
    safe_say(f'worker: {how} shutdown (MainProcess)')
  File "/usr/local/lib/python3.9/site-packages/celery/apps/worker.py", line 82, in safe_say
    print(f'\n{msg}', file=sys.__stderr__, flush=True)
BrokenPipeError: [Errno 32] Broken pipe
[2021-12-14 14:18:04,884: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/worker/consumer/consumer.py:361: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered back to the queue.
You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss setting.
In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2021-12-14 14:18:05,114: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 2.00 seconds... (1/100)

[2021-12-14 14:18:07,133: ERROR/MainProcess] consumer: Cannot connect to redis://redis:6379/0: Error -3 connecting to redis:6379. Temporary failure in name resolution..
Trying again in 4.00 seconds... (2/100)

[2021-12-15 18:51:34,075: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-15 18:51:34,148: INFO/MainProcess] mingle: searching for neighbors
[2021-12-15 18:51:35,305: INFO/MainProcess] mingle: all alone
[2021-12-15 18:51:35,410: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-15 18:51:35,419: INFO/MainProcess] celery@d1250202f854 ready.
[2021-12-15 18:51:38,916: INFO/MainProcess] Events of group {task} enabled by remote.
[2021-12-16 19:40:54,626: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-12-16 19:40:54,679: INFO/MainProcess] mingle: searching for neighbors
[2021-12-16 19:40:55,771: INFO/MainProcess] mingle: all alone
[2021-12-16 19:40:55,841: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2021-12-16 19:40:55,843: INFO/MainProcess] celery@a38e9192d2fb ready.
[2021-12-16 19:40:56,046: INFO/MainProcess] Events of group {task} enabled by remote.
[2022-01-11 16:11:19,526: INFO/MainProcess] Connected to redis://redis:6379/0
[2022-01-11 16:11:19,545: INFO/MainProcess] mingle: searching for neighbors
[2022-01-11 16:11:20,594: INFO/MainProcess] mingle: all alone
[2022-01-11 16:11:20,618: WARNING/MainProcess] /usr/local/lib/python3.9/site-packages/celery/fixups/django.py:203: UserWarning: Using settings.DEBUG leads to a memory
            leak, never use this setting in production environments!
  warnings.warn('''Using settings.DEBUG leads to a memory

[2022-01-11 16:11:20,620: INFO/MainProcess] celery@f758f699a9e0 ready.
[2022-01-11 16:11:23,423: INFO/MainProcess] Events of group {task} enabled by remote.
